services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./images:/images
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/images:ro
      - ./src/static:/app/src/static:ro
    depends_on:
      - app

volumes:
  db_data: