events {
    worker_connections 1024; #максимальна кількість одночасних підключень
}

http {
    include /etc/nginx/mime.types; #підключення стандартних MIME-типів файлів
    default_type application/octet-stream; #тип за замовчуванням для невідомих файлів

    upstream app {
        server app:8000; #вказуємо бекенд додаток на контейнері порт 8000
    }

    server {
        listen 8080; #порт на якому сервер
        client_max_body_size 100M; #максимальний розмір тіла запиту

        location /images/ {
            alias /images/; #файли з images на сервері віддаються з цієї директорії
            expires 1y; #кешування браузером на 1 рік
            add_header Cache-Control "public, immutable"; #заголовки для постійного кешування
        }

        location /static/ {
            alias /app/src/static/; #статичні файли віддаються з цієї директорії
            expires 1y; #кешування браузером на 1 рік
            add_header Cache-Control "public, immutable"; #заголовки для постійного кешування
        }

        location / {
            proxy_pass http://app; #проксі на бекенд додаток
            proxy_set_header Host $host; #передаємо хост із запиту на бекенд
            proxy_set_header X-Real-IP $remote_addr; #передаємо IP клієнта на бекенд
        }
    }
}