events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream app {
        server app:8000;
    }

    server {
        listen 8080;
        client_max_body_size 100M;

        location /images/ {
            alias /images/;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        location /static/ {
            alias /app/src/static/;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        location / {
            proxy_pass http://app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}